# Form implementation generated from reading ui file 'AddService.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        Form.setMinimumSize(QtCore.QSize(400, 300))
        Form.setMaximumSize(QtCore.QSize(400, 300))
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 381, 191))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.combo_users = QtWidgets.QComboBox(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_users.sizePolicy().hasHeightForWidth())
        self.combo_users.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.combo_users.setFont(font)
        self.combo_users.setPlaceholderText("")
        self.combo_users.setObjectName("combo_users")
        self.verticalLayout.addWidget(self.combo_users)
        self.box_title = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_title.sizePolicy().hasHeightForWidth())
        self.box_title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.box_title.setFont(font)
        self.box_title.setMaxLength(30)
        self.box_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.box_title.setObjectName("box_title")
        self.verticalLayout.addWidget(self.box_title)
        self.box_price = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_price.sizePolicy().hasHeightForWidth())
        self.box_price.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.box_price.setFont(font)
        self.box_price.setMaxLength(6)
        self.box_price.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.box_price.setObjectName("box_price")
        self.verticalLayout.addWidget(self.box_price)
        self.btn_save = QtWidgets.QPushButton(parent=Form)
        self.btn_save.setGeometry(QtCore.QRect(130, 220, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.btn_save.setFont(font)
        self.btn_save.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_save.setStyleSheet("background-color:green;color:white;border-radius:15px;")
        self.btn_save.setObjectName("btn_save")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.box_title.setPlaceholderText(_translate("Form", "عنوان الخدمة"))
        self.box_price.setPlaceholderText(_translate("Form", "السعر"))
        self.btn_save.setText(_translate("Form", "حفظ "))
