# Form implementation generated from reading ui file 'CreateEditUser.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets



class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 280)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(400, 280))
        Form.setMaximumSize(QtCore.QSize(400, 280))
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 80, 371, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.box_name = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget)
    

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_name.sizePolicy().hasHeightForWidth())
        self.box_name.setSizePolicy(sizePolicy)
        self.box_name.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.box_name.setFont(font)
        self.box_name.setObjectName("box_name")
        self.horizontalLayout.addWidget(self.box_name)
        self.box_phone = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_phone.sizePolicy().hasHeightForWidth())
        self.box_phone.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.box_phone.setFont(font)
        self.box_phone.setObjectName("box_phone")
        self.horizontalLayout.addWidget(self.box_phone)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 150, 371, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.box_balance = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_balance.sizePolicy().hasHeightForWidth())
        self.box_balance.setSizePolicy(sizePolicy)
        self.box_balance.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.box_balance.setFont(font)
        self.box_balance.setObjectName("box_balance")
        self.horizontalLayout_2.addWidget(self.box_balance)
        self.btn_save = QtWidgets.QPushButton(parent=Form)
        self.btn_save.setGeometry(QtCore.QRect(140, 210, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_save.setFont(font)
        self.btn_save.setObjectName("btn_save")
        self.btn_save.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_save.setStyleSheet("QPushButton{\n"
"    border-radius:15px;\n"
"    color:white;\n"
"    background-color:#239b56;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:#283747;\n"
"}")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(100, 30, 250, 41))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.box_name.setPlaceholderText(_translate("Form", "الإسم"))
        self.box_phone.setPlaceholderText(_translate("Form", "الهاتف"))
        self.box_balance.setPlaceholderText(_translate("Form", "مبلغ الحساب"))
        self.btn_save.setText(_translate("Form", "أضف الآن"))
        self.label.setText(_translate("Form", "إضافة مستخدم"))

        # simple validator
        self.box_name.setMaxLength(20)

        self.box_phone.setValidator(QtGui.QIntValidator())
        self.box_phone.setMaxLength(10)

        self.box_balance.setValidator(QtGui.QIntValidator())
        self.box_balance.setMaxLength(6)
