# Form implementation generated from reading ui file 'ShowTotalIncome.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(550, 500)
        Form.setMinimumSize(QtCore.QSize(550, 500))
        Form.setMaximumSize(QtCore.QSize(550, 500))
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(330, 90, 171, 81))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(310, 10, 191, 81))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(320, 170, 191, 81))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.sales_total = QtWidgets.QLCDNumber(parent=Form)
        self.sales_total.setGeometry(QtCore.QRect(10, 20, 231, 61))
        self.sales_total.setStyleSheet("color:green")
        self.sales_total.setDigitCount(6)
        self.sales_total.setProperty("value", 0.0)
        self.sales_total.setObjectName("sales_total")
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setGeometry(QtCore.QRect(10, 280, 501, 81))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.total_income = QtWidgets.QLCDNumber(parent=Form)
        self.total_income.setGeometry(QtCore.QRect(60, 370, 411, 111))
        self.total_income.setStyleSheet("color:green")
        self.total_income.setDigitCount(6)
        self.total_income.setProperty("value", 0.0)
        self.total_income.setObjectName("total_income")
        self.services_total = QtWidgets.QLCDNumber(parent=Form)
        self.services_total.setGeometry(QtCore.QRect(10, 100, 231, 61))
        self.services_total.setStyleSheet("color:green")
        self.services_total.setDigitCount(6)
        self.services_total.setProperty("value", 0.0)
        self.services_total.setObjectName("services_total")
        self.expenses_total = QtWidgets.QLCDNumber(parent=Form)
        self.expenses_total.setGeometry(QtCore.QRect(10, 180, 231, 61))
        self.expenses_total.setStyleSheet("color:red")
        self.expenses_total.setDigitCount(6)
        self.expenses_total.setProperty("value", 0.0)
        self.expenses_total.setObjectName("expenses_total")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "الخدمات :"))
        self.label_2.setText(_translate("Form", "المبيعات :"))
        self.label_3.setText(_translate("Form", "المصاريف :"))
        self.label_4.setText(_translate("Form", "الدخل الشهري الصافي "))
