# Form implementation generated from reading ui file 'ShowOperations.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 300)
        Form.setMinimumSize(QtCore.QSize(800, 300))
        Form.setMaximumSize(QtCore.QSize(800, 300))
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(170, 10, 441, 41))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.box_search = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_search.sizePolicy().hasHeightForWidth())
        self.box_search.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.box_search.setFont(font)
        self.box_search.setObjectName("box_search")
        self.verticalLayout.addWidget(self.box_search)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 60, 781, 221))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.operations_table = QtWidgets.QTableWidget(parent=self.verticalLayoutWidget_2)
        self.operations_table.setObjectName("operations_table")
        self.operations_table.setColumnCount(6)
        self.operations_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.operations_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.operations_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.operations_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.operations_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.operations_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.operations_table.setHorizontalHeaderItem(5, item)
        self.verticalLayout_2.addWidget(self.operations_table)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.box_search.setPlaceholderText(_translate("Form", "أكتب هنا للبحث"))
        item = self.operations_table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "المرجع"))
        item = self.operations_table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "السلعة"))
        item = self.operations_table.horizontalHeaderItem(2)
        item.setText(_translate("Form", "الكمية"))
        item = self.operations_table.horizontalHeaderItem(3)
        item.setText(_translate("Form", "السعر"))
        item = self.operations_table.horizontalHeaderItem(4)
        item.setText(_translate("Form", "المجموع"))
        item = self.operations_table.horizontalHeaderItem(5)
        item.setText(_translate("Form", "التاريخ"))
